What is Numpy?

NumPy is a Python library that provides support for large, multi-dimensional arrays and matrices, as well as a wide range of mathematical operations to manipulate these arrays. It is widely used in scientific computing, data analysis, and machine learning.

How to install Numpy?

To install NumPy, you can use pip, which is a package installer for Python. Here are the steps to install NumPy using pip:

Open a command prompt or terminal on your computer.
Type the following command to install NumPy using pip: pip install numpy
Press Enter and wait for the installation to complete.

Alternatively, if you are using Anaconda, you can install NumPy by opening the Anaconda prompt and typing the following command:

conda install numpy

Once NumPy is installed, you can import it in your Python code using the following statement:

import numpy as np

In [1]:
import numpy as np

#Now the NumPy package can be referred to as np instead of numpy.


In [2]:

# To check your installed version of Numpy use the command

print (np.__version__)

1.22.3


np.array() -  This command creates a NumPy array from a Python list or tuple.

In [3]:
#Create a 1 dimension array

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [4]:
#create 2D arrays

b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [5]:
#create 3D arrays

c=np.array([[[1,2],[2,4]],[[3,4],[5,6]]])
print(c)

[[[1 2]
  [2 4]]

 [[3 4]
  [5 6]]]


In [6]:
# Check the dimensions of array
# To check the dimensions of a NumPy array, you can use the ndim attribute


print(a.ndim)
print(b.ndim)
print(c.ndim)


1
2
3


In [7]:
#Create a 3-D array with ones on the diagonal and zeros elsewhere.

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#np.zeros() - This command creates a NumPy array filled with zeros.#
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#Create a new array of 3*2 float numbers, filled with ones and type float.

np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
#Create a new array of 2*5 uints, filled with 6.

np.full((2,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [12]:
np.ones([2, 5], dtype=np.uint) * 6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

# Numerical ranges

In [13]:
#Create an array of 2, 4, 6, 8, ..., 100.

np.arange(2,101,2)


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [14]:
#Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

np.linspace(3,10,50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [15]:
#Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

np.logspace(3., 10., 50, endpoint=False)

array([1.00000000e+03, 1.38038426e+03, 1.90546072e+03, 2.63026799e+03,
       3.63078055e+03, 5.01187234e+03, 6.91830971e+03, 9.54992586e+03,
       1.31825674e+04, 1.81970086e+04, 2.51188643e+04, 3.46736850e+04,
       4.78630092e+04, 6.60693448e+04, 9.12010839e+04, 1.25892541e+05,
       1.73780083e+05, 2.39883292e+05, 3.31131121e+05, 4.57088190e+05,
       6.30957344e+05, 8.70963590e+05, 1.20226443e+06, 1.65958691e+06,
       2.29086765e+06, 3.16227766e+06, 4.36515832e+06, 6.02559586e+06,
       8.31763771e+06, 1.14815362e+07, 1.58489319e+07, 2.18776162e+07,
       3.01995172e+07, 4.16869383e+07, 5.75439937e+07, 7.94328235e+07,
       1.09647820e+08, 1.51356125e+08, 2.08929613e+08, 2.88403150e+08,
       3.98107171e+08, 5.49540874e+08, 7.58577575e+08, 1.04712855e+09,
       1.44543977e+09, 1.99526231e+09, 2.75422870e+09, 3.80189396e+09,
       5.24807460e+09, 7.24435960e+09])

# NumPy Array Indexing

In [16]:
#Get the first element from the following array:

a= np.array([1,2,3,4])

a[0] #Index starts from 0

1

In [17]:
#Get the second element from the following array.

a[1]

2

In [18]:
#Access 2-D Arrays
#access 2nd element on 1st row

b= np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b[1,1]


[[1 2 3 4]
 [5 6 7 8]]


6

In [19]:
#Access the element on the 2nd row, 4th column:

a=np.array([[1,2,3,4],[5,6,7,8],[4,2,1,1]])
print(a)
a[2,3]

[[1 2 3 4]
 [5 6 7 8]
 [4 2 1 1]]


1

In [20]:
#Access 3-D Arrays

#Access the third element of the second array of the first array:


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr[0,1,2]

6

#Negative Indexing

In [21]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
arr[1,-1] #2nd row and last column

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


10

Slicing arrays

In [22]:
#A-Slice elements from index 1 to index 6 from the following array

arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9])

arr[1:7]

array([2, 3, 4, 5, 6, 7])

In [23]:
#Slice elements from index 2 to the end of the array

arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
#Slice elements from the beginning to index 5
arr[:5]

array([1, 2, 3, 4, 5])

In [25]:
#Return every other element from index 1 to index 6

arr[1:6:2]

array([2, 4, 6])

In [26]:
#Return every other element from the entire array

arr[::2]

array([1, 3, 5, 7, 9])

In [27]:
#Slicing 2-D Arrays

#From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr[1,1:4]

array([7, 8, 9])

In [28]:
#From both elements, return index 2:

arr[:,2]

array([3, 8])

In [29]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

NumPy Data Types
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [30]:
#Checking the Data Type of an Array

a = np.array([1, 2, 3, 4])
a.dtype

dtype('int32')

In [31]:
#data type of an array containing strings:

b=np.array(['a','b','c'])
b.dtype

dtype('<U1')

In [32]:
b=np.array(['Data','Numpy','Pandas'])
b.dtype

dtype('<U6')

In [33]:
#Creating Arrays With a required Data Type

a = np.array([1, 2, 3, 4], dtype='S')
a.dtype

dtype('S1')

In [34]:
#changing array from int to float
a = np.array([1, 2, 3, 4], dtype='f')
print(a.dtype)
print(a)

float32
[1. 2. 3. 4.]


In [35]:
#Change data type from integer to boolean:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# NumPy Array Shape

In NumPy, the shape attribute is used to get the dimensions of an array. It returns a tuple representing the size of each dimension of the array.

In [36]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [37]:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('shape of array :', arr.shape)

[[[1 2 3 4]]]
shape of array : (1, 1, 4)


# NumPy Array Reshaping

NumPy Array Reshaping is a technique to change the shape of an existing array without changing its data. The reshape() function in NumPy is used to reshape an array. It takes a tuple as an argument that specifies the new shape of the array.

In [38]:
# Create a 2-dimensional NumPy array with 4 rows and 6 columns
arr = np.arange(24).reshape(4, 6)

# Reshape the array to have 6 rows and 4 columns
new_arr = arr.reshape(6, 4)

# Print both arrays
print(arr)
print(new_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [39]:
# Create a 3-dimensional NumPy array with 2 planes, 3 rows, and 4 columns
arr = np.arange(24).reshape(2, 3, 4)

# Reshape the array to have 4 planes, 3 rows, and 2 columns
new_arr = arr.reshape(4, 3, 2)

# Print both arrays
print(arr)
print('*************')
print(new_arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
*************
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


# NumPy Array Iterating

NumPy Array Iterating refers to accessing each element of an array using loops or other iterators. In NumPy, we can iterate over the elements of an array using various techniques like for loops, while loops, and NumPy functions like nditer().

In [40]:
#Iterating over the elements of a 1-D array using a for loop:

arr = np.array([1, 2, 3, 4, 5])
for i in arr:
    print(i)

1
2
3
4
5


In [41]:
# Iterate over the elements of the array using nditer()
for i in np.nditer(arr):
    print(i)

1
2
3
4
5


In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
               
# Iterate over the elements of the array using nested loops
for x in arr:
  print(x)

[1 2 3]
[4 5 6]
[7 8 9]


In [43]:
#Iterate on each scalar element of the 2-D array:

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9


In [44]:
# Iterate over the elements of the array using nditer()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for element in np.nditer(arr):
               print(element)
               
    

1
2
3
4
5
6
7
8
9


Iterating 3-D Arrays

In [45]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [46]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [47]:
#Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


Joins

NumPy Array Joins refer to the process of combining two or more arrays to form a new array. There are several ways to join arrays in NumPy, including concatenate(), stack(), hstack(), and vstack().

In [48]:
#concatenate(): This function is used to concatenate two or more arrays along a specified axis.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))

print(c)

[1 2 3 4 5 6]


In [49]:
#Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [50]:
#stack(): This function is used to stack arrays along a new axis

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.stack((a, b))

print(c)

[[1 2 3]
 [4 5 6]]


In [51]:
#hstack(): This function is used to horizontally stack two or more arrays.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a, b))

print(c)

[1 2 3 4 5 6]


In [52]:
#vstack(): This function is used to vertically stack two or more arrays.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))

print(c)

[[1 2 3]
 [4 5 6]]


In [53]:
#Stacking Along Height (depth)

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


#Split

In NumPy, array splitting refers to the process of breaking a single array into multiple smaller arrays. We can split NumPy arrays using the split(), hsplit(), and vsplit() functions

In [54]:
# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Split the array into two equal-sized arrays along the first axis
b, c = np.split(a, 2)

print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [55]:
#If the array has less elements than required, it will adjust from the end accordingly.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [56]:
#Split the 2-D array into three 2-D arrays along rows.

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(a, 3, axis=1)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


# Numpy Search

In NumPy, searching an array means finding the indices of elements that satisfy a given condition. The functions where(), argwhere(), and nonzero() can be used to search for elements

In [57]:
# Create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Find the indices of elements that are greater than 5
indices = np.where(a > 5)

print(indices)

(array([5, 6, 7, 8], dtype=int64),)


In [58]:
# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the indices of elements that are greater than 5
indices = np.argwhere(a > 5)

print(indices)

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


# Sorting

NumPy sorting refers to the process of arranging the elements of an array in a particular order. NumPy provides several functions for sorting arrays, such as sort()

In [59]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [60]:
#Sort the array alphabetically:

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [61]:
#Sort a boolean array:

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [62]:
#Sort a 2-D array:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
